<a href="https://colab.research.google.com/github/dymiyata/python-pro-summer-2026/blob/main/intro_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

NumPy (Numerical Python) is a Python library for handling numerical data in Python.

Let's import it.

In [1]:
import numpy as np

The fundamental data structure that NumPy uses to store and manipulate data is a NumPy array. We can create one from a Python list by using `np.array(some_list)`.

In [4]:
list1 = [1, "hello", 87, True]

In [6]:
arr = np.array([1,2,3])

In [8]:
print(arr[0])

1


Unlike Python lists, NumPy arrays are *true* arrays in the computer science sense. Specifically:
- all elements of the array must have the same data type (e.g. `int64`, `float64`, `bool_`, `str_`, etc...)
  - NumPy will try to automatically detect the data type for elements of a given array
  - You can also manually specify it and NumPy will try its best to convert to the specified data type.
  - To specify the data type, add the `dtype` argument to the `np.array` function
  - To check the data type, you can run `array.dtype`
- The array is stored in a contiguous block of memory with only enough space to store the array itself.
  - This means if you want to add elements to the array (i.e. make the array bigger), you need to create a completely new array.

### Multidimensional Arrays

Sometimes, we want to organize our data in multiple dimensions (like in a table or a matrix). NumPy arrays can be multidimensional!  For now, we will just focus on 1D and 2D arrays, but you can make higher dimensional arrays too.

To create a 2D array, you can again use the `np.array()` function, but this time, input a list of lists (the "rows" of your array).

In [9]:
fruits = [1, 2, 3, 4, 5]

In [12]:
fruits2D = [[1, 2, 3], [2, 7, 9], [15, 1, 0]]

In [14]:
fruits2D[0][2]

3

In [16]:
arr2d = np.array([
    [1, 2, 3],
    [5, 4, 2],
    [7, 8, 9]
])

In [18]:
arr2d[1,1]

np.int64(4)

To check the dimensions of an array, we can use the command `array.shape`.  If it's a 2D array, it will return a pair where the first coordinate is the number of rows and the second coordinate is the number of columns.

In [19]:
arr2d.shape

(3, 3)

In [20]:
arr.shape

(3,)

### Array Creation Helper Functions

There are some nice helper functions for creating arrays.

We can use `np.zeros(shape)` to create an array of all zeros with the specified shape.

In [21]:
print(np.zeros((3,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Similarly, we can use `np.ones()` to create an array of all ones.

In [22]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

For other values, we can use `np.full()` in a similar way.  However, we need to specificy the fill value as a second argument.

Let's try to make a $4 \times 5$ array where all the entries are 9.

In [24]:
print(np.full((2,4), 10))

[[10 10 10 10]
 [10 10 10 10]]


With `np.full`, you can even use a list as the specified value to get an array where all of the rows are the same.

In [27]:
np.full((3,3), [1,2,3])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

We can use `np.arange()` (read as "a-range" not "arrange") to get an array of evenly spaced values.  It behaves much like the Python `range()` function.
- Here we specify a starting value, a stopping value, and a step size.  
- `np.arange()` will create a 1D array starting at the starting value, in steps equal to the step size.  It will stop at the last step which is *strictly smaller* than the stopping value.

In [34]:
for i in range(-5, 10, 2):
  print(i)

-5
-3
-1
1
3
5
7
9


In [35]:
np.arange(3,9,2)

array([3, 5, 7])

Sometimes, we want evenly spaced values like `arange` gives us but rather than knowing the step size, we instead know *how many* elements we want.  In this case, it's easier to use `np.linspace` instead.  Again, we specify a starting value and a stopping value.  However, now the third argument isn't the step size, it's the number of elements we want.

In [41]:
np.linspace(3,9,33)

array([3.    , 3.1875, 3.375 , 3.5625, 3.75  , 3.9375, 4.125 , 4.3125,
       4.5   , 4.6875, 4.875 , 5.0625, 5.25  , 5.4375, 5.625 , 5.8125,
       6.    , 6.1875, 6.375 , 6.5625, 6.75  , 6.9375, 7.125 , 7.3125,
       7.5   , 7.6875, 7.875 , 8.0625, 8.25  , 8.4375, 8.625 , 8.8125,
       9.    ])

### Accessing values/slices of an array

Now that we know how to create arrays, how can we access the data from them?

A 1D array behaves basically the same as a Python list.

In [42]:
arr = np.array([[2,3,4, 5],
               [5,6,7, 8],
               [8,9,10, 11]])

If we have a 2D array, then we can access values using two indices.  For example `array[i,j]` with give the element in the `i`th row and `j`th column.

In [43]:
arr[0, 1:3]

array([3, 4])

In [44]:
arr[:, 1:3]

array([[ 3,  4],
       [ 6,  7],
       [ 9, 10]])

# Math with NumPy

One of the main reasons we use NumPy arrays is because it can do numerical operations **fast**.

Suppose we have two lists of integers and we want to add each entry of the first list to its corresponding entry in the second list and then get a resulting list.

In [72]:
list1 = list(range(10000000))
list2 = list(range(0,20000000,2))

Let's do it with Python lists.

In [73]:
import time
start = time.time()

result = []
for i in range(len(list1)):
  result.append(list1[i] + list2[i])
end = time.time()

print(end - start)

1.0900051593780518


Now let's do it the faster way with NumPy arrays.

In [74]:
arr1 = np.array(list1)
arr2 = np.array(list2)

In [79]:
start = time.time()
arr3 = arr1 + arr2
end = time.time()
print(end - start)

0.015290975570678711


NumPy does things much faster because it *vectorizes* the operation.  Essentially, it's doing all of the operations in *parallel* rather than adding each pair one at a time. (This uses more memory, but more often than not, speed is the limiting factor, not memory).